using System.IO;
using System.Net;
using System.Text;
using RTMPProjector.Models;

namespace RTMPProjector.Services;

/// <summary>
/// Minimal HTTP server that serves the live player website.
/// Runs on localhost:{PlayerPort} — exposed to the internet via Cloudflare Tunnel.
/// config.js is generated live from current app settings so the website always
/// reflects the active stream key, title, and password without any manual editing.
/// </summary>
public class WebPlayerService : IDisposable
{
    private static readonly string WebDir =
        Path.Combine(AppContext.BaseDirectory, "web");

    private readonly HttpListener _listener = new();
    private AppSettings? _settings;
    private CancellationTokenSource? _cts;
    private Task? _loop;

    public event Action<string>? LogMessage;

    public bool IsRunning { get; private set; }

    public void Start(AppSettings settings)
    {
        if (IsRunning) return;

        _settings = settings;

        _listener.Prefixes.Clear();
        _listener.Prefixes.Add($"http://localhost:{settings.PlayerPort}/");

        try
        {
            _listener.Start();
        }
        catch (Exception ex)
        {
            LogMessage?.Invoke($"[web-player] Failed to start on port {settings.PlayerPort}: {ex.Message}");
            return;
        }

        IsRunning = true;
        _cts = new CancellationTokenSource();
        _loop = Task.Run(() => ListenLoop(_cts.Token));
        LogMessage?.Invoke($"[web-player] Listening on http://localhost:{settings.PlayerPort}/");
    }

    public void Stop()
    {
        if (!IsRunning) return;
        _cts?.Cancel();
        _listener.Stop();
        _loop?.Wait(TimeSpan.FromSeconds(2));
        IsRunning = false;
        LogMessage?.Invoke("[web-player] Stopped.");
    }

    private async Task ListenLoop(CancellationToken ct)
    {
        while (!ct.IsCancellationRequested)
        {
            try
            {
                var ctx = await _listener.GetContextAsync().WaitAsync(ct);
                _ = Task.Run(() => HandleRequest(ctx), ct);
            }
            catch (OperationCanceledException) { break; }
            catch (HttpListenerException) { break; }
            catch { }
        }
    }

    private void HandleRequest(HttpListenerContext ctx)
    {
        try
        {
            var path = ctx.Request.Url?.AbsolutePath.TrimEnd('/') ?? "/";
            if (path == "") path = "/";

            switch (path)
            {
                case "/":
                case "/index.html":
                    ServeFile(ctx.Response, "index.html", "text/html; charset=utf-8");
                    break;
                case "/style.css":
                    ServeFile(ctx.Response, "style.css", "text/css; charset=utf-8");
                    break;
                case "/player.js":
                    ServeFile(ctx.Response, "player.js", "application/javascript; charset=utf-8");
                    break;
                case "/config.js":
                    ServeConfigJs(ctx.Response);
                    break;
                default:
                    ctx.Response.StatusCode = 404;
                    ctx.Response.Close();
                    break;
            }
        }
        catch { ctx.Response.Abort(); }
    }

    private void ServeConfigJs(HttpListenerResponse resp)
    {
        var s = _settings;
        if (s == null) { resp.StatusCode = 503; resp.Close(); return; }

        var streamBase = string.IsNullOrWhiteSpace(s.TunnelHostname)
            ? $"http://localhost:{s.HlsPort}"
            : $"https://{s.TunnelHostname}";

        var first = s.StreamKeys.FirstOrDefault();
        var hlsUrl = first != null
            ? $"{streamBase}/live/{first.Key}/index.m3u8"
            : "";
        var title    = first?.Name ?? "Live Stream";
        var password = s.WebStreamPassword ?? "";

        var js = $"""
            // Auto-generated by RTMP Projector — do not edit manually
            window.STREAM_CONFIG = {{
              hlsUrl:        '{EscJs(hlsUrl)}',
              title:         '{EscJs(title)}',
              password:      '{EscJs(password)}',
              retryInterval: 10,
            }};
            """;

        WriteText(resp, js, "application/javascript; charset=utf-8");
    }

    private static void ServeFile(HttpListenerResponse resp, string filename, string contentType)
    {
        var path = Path.Combine(WebDir, filename);
        if (!File.Exists(path)) { resp.StatusCode = 404; resp.Close(); return; }

        var bytes = File.ReadAllBytes(path);
        resp.ContentType = contentType;
        resp.AddHeader("Cache-Control", "no-store");
        resp.ContentLength64 = bytes.Length;
        resp.OutputStream.Write(bytes);
        resp.Close();
    }

    private static void WriteText(HttpListenerResponse resp, string text, string contentType)
    {
        var bytes = Encoding.UTF8.GetBytes(text);
        resp.ContentType = contentType;
        resp.AddHeader("Cache-Control", "no-store");
        resp.ContentLength64 = bytes.Length;
        resp.OutputStream.Write(bytes);
        resp.Close();
    }

    private static string EscJs(string s) =>
        s.Replace("\\", "\\\\").Replace("'", "\\'").Replace("\n", "\\n");

    public void Dispose() => Stop();
}
